### ISSUE TITLE
Footer?

### ISSUE THREAD

**Issue by Harbane** [Harbane/Harbane_web#2]
The footer is not complete and needs alot of work.
it need to have 
- copyright to creator
- link to a "terms and conditions" page (page coming soon)
- link to a "contact us" page 
- link to Acknowledgments page (page coming soon)
- suggestions?

**Comment by wally-the-tally** [comment]
yea, no worries. i got this, any specific color and font.

**Comment by Harbane** [comment]
Not really
But here is just a css overview of the website

***@***.***
